// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return <div
    className={"min-h-screen flex items-center justify-center"}
  >
    {"rescript-pomodoro loading..."}
  </div>;
}

let make = App;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
