// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tasks from "./Tasks.res.jsx";
import * as Timer from "./Timer.res.jsx";
import * as React from "react";
import * as Sonner from "sonner";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as JsxRuntime from "react/jsx-runtime";

function reducer(state, action) {
  if (typeof action !== "object") {
    switch (action) {
      case "TimerStart" :
        return {
          timer: Timer.start(state.timer),
          tasks: state.tasks,
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: state.settingsOpen
        };
      case "TimerPause" :
        return {
          timer: Timer.pause(state.timer),
          tasks: state.tasks,
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: state.settingsOpen
        };
      case "TimerResume" :
        return {
          timer: Timer.resume(state.timer),
          tasks: state.tasks,
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: state.settingsOpen
        };
      case "TimerReset" :
        return {
          timer: Timer.reset(state.timer),
          tasks: state.tasks,
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: state.settingsOpen
        };
      case "TimerTick" :
        let match = Timer.tick(state.timer);
        let t2 = match[0];
        if (match[1]) {
          let match$1 = t2.phase;
          switch (match$1) {
            case "Working" :
              Sonner.toast.success("Break over. Focus time!");
              break;
            case "OnBreak" :
              Sonner.toast.success("Session complete! Take a break.");
              break;
            case "Idle" :
            case "Paused" :
              break;
          }
        }
        return {
          timer: t2,
          tasks: state.tasks,
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: state.settingsOpen
        };
      case "TaskAdd" :
        if (state.newTaskTitle === "") {
          return state;
        } else {
          return {
            timer: state.timer,
            tasks: Tasks.addTask(state.tasks, state.newTaskTitle, state.nextTaskId),
            nextTaskId: state.nextTaskId + 1 | 0,
            newTaskTitle: "",
            settingsOpen: state.settingsOpen
          };
        }
      case "OpenSettings" :
        return {
          timer: state.timer,
          tasks: state.tasks,
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: true
        };
      case "CloseSettings" :
        return {
          timer: state.timer,
          tasks: state.tasks,
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: false
        };
    }
  } else {
    switch (action.TAG) {
      case "TaskToggle" :
        return {
          timer: state.timer,
          tasks: Tasks.toggleTask(state.tasks, action._0),
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: state.settingsOpen
        };
      case "TaskDelete" :
        return {
          timer: state.timer,
          tasks: Tasks.deleteTask(state.tasks, action._0),
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: state.settingsOpen
        };
      case "SetNewTaskTitle" :
        return {
          timer: state.timer,
          tasks: state.tasks,
          nextTaskId: state.nextTaskId,
          newTaskTitle: action._0,
          settingsOpen: state.settingsOpen
        };
      case "UpdateWorkSecs" :
        let secs = action._0;
        let init = state.timer;
        let newTimer_phase = init.phase;
        let newTimer_timeLeft = init.timeLeft;
        let newTimer_breakSecs = init.breakSecs;
        let newTimer_sessionCount = init.sessionCount;
        let newTimer = {
          phase: newTimer_phase,
          timeLeft: newTimer_timeLeft,
          workSecs: secs,
          breakSecs: newTimer_breakSecs,
          sessionCount: newTimer_sessionCount
        };
        let match$2 = newTimer_phase;
        let finalTimer;
        finalTimer = match$2 === "Idle" ? ({
            phase: newTimer_phase,
            timeLeft: secs,
            workSecs: secs,
            breakSecs: newTimer_breakSecs,
            sessionCount: newTimer_sessionCount
          }) : newTimer;
        return {
          timer: finalTimer,
          tasks: state.tasks,
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: state.settingsOpen
        };
      case "UpdateBreakSecs" :
        let init$1 = state.timer;
        return {
          timer: {
            phase: init$1.phase,
            timeLeft: init$1.timeLeft,
            workSecs: init$1.workSecs,
            breakSecs: action._0,
            sessionCount: init$1.sessionCount
          },
          tasks: state.tasks,
          nextTaskId: state.nextTaskId,
          newTaskTitle: state.newTaskTitle,
          settingsOpen: state.settingsOpen
        };
    }
  }
}

function App(props) {
  let initialTimer = Timer.makeInitial(1500, 300);
  let match = React.useReducer(reducer, {
    timer: initialTimer,
    tasks: [],
    nextTaskId: 1,
    newTaskTitle: "",
    settingsOpen: false
  });
  let dispatch = match[1];
  let state = match[0];
  React.useEffect(() => {
    let match = state.timer.phase;
    if (match !== "Working") {
      return;
    }
    let id = setInterval(() => dispatch("TimerTick"), 1000);
    return () => {
      clearInterval(id);
    };
  }, [state.timer.phase]);
  let match$1 = state.timer.phase;
  let phaseLabel;
  switch (match$1) {
    case "Idle" :
      phaseLabel = "Ready";
      break;
    case "Working" :
      phaseLabel = "Focus";
      break;
    case "OnBreak" :
      phaseLabel = "Break";
      break;
    case "Paused" :
      phaseLabel = "Paused";
      break;
  }
  let match$2 = state.timer.phase;
  let total;
  switch (match$2) {
    case "Working" :
    case "OnBreak" :
      total = state.timer.timeLeft;
      break;
    case "Idle" :
    case "Paused" :
      total = state.timer.workSecs;
      break;
  }
  let progress;
  if (total > 0) {
    let match$3 = state.timer.phase;
    let totalTime;
    switch (match$3) {
      case "OnBreak" :
        totalTime = state.timer.breakSecs;
        break;
      case "Idle" :
      case "Working" :
      case "Paused" :
        totalTime = state.timer.workSecs;
        break;
    }
    progress = Primitive_int.div((totalTime - state.timer.timeLeft | 0) * 100 | 0, totalTime);
  } else {
    progress = 0;
  }
  let n = state.timer.sessionCount;
  let sessionText = n !== 0 ? (
      n !== 1 ? n.toString() + " sessions" : "1 session"
    ) : "0 sessions";
  let match$4 = state.timer.phase;
  let tmp;
  switch (match$4) {
    case "Idle" :
      tmp = <button
        className={"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-9 px-4 py-2"}
        onClick={param => dispatch("TimerStart")}
      >
        {"Start"}
      </button>;
      break;
    case "Working" :
      tmp = <button
        className={"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2"}
        onClick={param => dispatch("TimerPause")}
      >
        {"Pause"}
      </button>;
      break;
    case "OnBreak" :
      tmp = <button
        className={"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2"}
        onClick={param => dispatch("TimerPause")}
      >
        {"Pause Break"}
      </button>;
      break;
    case "Paused" :
      tmp = <button
        className={"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-9 px-4 py-2"}
        onClick={param => dispatch("TimerResume")}
      >
        {"Resume"}
      </button>;
      break;
  }
  let match$5 = state.timer.phase;
  let tmp$1;
  switch (match$5) {
    case "Working" :
      tmp$1 = "ring-1 ring-emerald-900/50";
      break;
    case "OnBreak" :
      tmp$1 = "ring-1 ring-sky-900/50";
      break;
    case "Idle" :
    case "Paused" :
      tmp$1 = "";
      break;
  }
  return <div
    className={"min-h-screen bg-background text-foreground flex flex-col items-center px-4 py-6 sm:p-8 pb-[env(safe-area-inset-bottom)] pt-[env(safe-area-inset-top)]"}
  >
    <Sonner.Toaster
      position={"bottom-center"}
      richColors={true}
    />
    <button
      className={"absolute top-4 right-4 inline-flex items-center justify-center size-9 rounded-md hover:bg-accent hover:text-accent-foreground transition-colors"}
      onClick={param => dispatch("OpenSettings")}
    >
      <svg
        height={"24"}
        width={"24"}
        fill={"none"}
        stroke={"currentColor"}
        strokeLinecap={"round"}
        strokeLinejoin={"round"}
        strokeWidth={"2"}
        viewBox={"0 0 24 24"}
        xmlns={"http://www.w3.org/2000/svg"}
      >
        <path
          d={"M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"}
        />
        <circle
          cx={"12"}
          cy={"12"}
          r={"3"}
        />
      </svg>
    </button>
    <div
      className={"w-full max-w-md bg-card text-card-foreground rounded-xl border shadow-sm px-6 py-6 mb-6 " + tmp$1}
    >
      <div
        className={"text-center mb-4"}
      >
        <span
          className={"text-muted-foreground text-sm uppercase tracking-wider"}
        >
          {phaseLabel}
        </span>
      </div>
      <div
        className={"text-center mb-6"}
      >
        <span
          className={"text-6xl sm:text-7xl font-mono font-bold tracking-tight"}
        >
          {Timer.formatTime(state.timer.timeLeft)}
        </span>
      </div>
      <div
        className={"bg-primary/20 relative h-2 w-full overflow-hidden rounded-full"}
      >
        <div
          className={"bg-primary h-full w-full flex-1 transition-all"}
          style={{
            transform: "translateX(-" + (100 - progress | 0).toString() + "%)"
          }}
        />
      </div>
      <div
        className={"flex justify-center gap-3"}
      >
        {tmp}
        <button
          className={"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2"}
          onClick={param => dispatch("TimerReset")}
        >
          {"Reset"}
        </button>
      </div>
    </div>
    <div
      className={"mb-8"}
    >
      <span
        className={"inline-flex items-center justify-center rounded-full border border-transparent px-3 py-1 text-xs font-medium bg-secondary text-secondary-foreground"}
      >
        {sessionText}
      </span>
    </div>
    <div
      className={"w-full max-w-md"}
    >
      <div
        className={"flex gap-2 mb-4"}
      >
        <input
          className={"dark:bg-input/30 border-input h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]"}
          inputMode={"text"}
          placeholder={"Add a task..."}
          type={"text"}
          value={state.newTaskTitle}
          onKeyDown={e => {
            if (e.key === "Enter") {
              return dispatch("TaskAdd");
            }
          }}
          onChange={e => {
            let value = e.target.value;
            dispatch({
              TAG: "SetNewTaskTitle",
              _0: value
            });
          }}
        />
        <button
          className={"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-9 px-4 py-2"}
          onClick={param => dispatch("TaskAdd")}
        >
          {"Add"}
        </button>
      </div>
      <div
        className={"max-h-64 sm:max-h-80 overflow-y-auto space-y-2 pr-1"}
      >
        {Belt_Array.map(state.tasks, task => <div
          key={task.id.toString()} 
          className={"flex items-center gap-3 p-3 bg-zinc-900 border border-zinc-800 rounded-lg group"}
        >
          <input
            className={"w-5 h-5 rounded border-zinc-600 bg-zinc-800 text-emerald-600 focus:ring-emerald-500 focus:ring-offset-zinc-900"}
            checked={task.done_}
            type={"checkbox"}
            onChange={param => dispatch({
              TAG: "TaskToggle",
              _0: task.id
            })}
          />
          <span
            className={task.done_ ? "flex-1 line-through text-zinc-500" : "flex-1 text-zinc-200"}
          >
            {task.title}
          </span>
          <button
            className={"sm:opacity-0 sm:group-hover:opacity-100 opacity-100 p-2 min-w-[44px] min-h-[44px] flex items-center justify-center hover:bg-zinc-800 rounded transition-opacity"}
            onClick={param => dispatch({
              TAG: "TaskDelete",
              _0: task.id
            })}
          >
            <svg
              className={"text-zinc-500 hover:text-red-400"}
              height={"18"}
              width={"18"}
              fill={"none"}
              stroke={"currentColor"}
              strokeLinecap={"round"}
              strokeLinejoin={"round"}
              strokeWidth={"2"}
              viewBox={"0 0 24 24"}
              xmlns={"http://www.w3.org/2000/svg"}
            >
              <path
                d={"M3 6h18"}
              />
              <path
                d={"M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"}
              />
              <path
                d={"M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"}
              />
            </svg>
          </button>
        </div>)}
      </div>
    </div>
    {state.settingsOpen ? <div
        className={"fixed inset-0 bg-black/60 flex items-center justify-center z-50"}
        onClick={param => dispatch("CloseSettings")}
      >
        <div
          className={"bg-zinc-900 border border-zinc-800 rounded-2xl p-6 w-full max-w-sm mx-4 shadow-2xl"}
          onClick={e => {
            e.stopPropagation();
          }}
        >
          <div
            className={"flex justify-between items-center mb-6"}
          >
            <h2
              className={"text-xl font-semibold text-zinc-50"}
            >
              {"Settings"}
            </h2>
            <button
              className={"p-1 hover:bg-zinc-800 rounded transition-colors"}
              onClick={param => dispatch("CloseSettings")}
            >
              <svg
                className={"text-zinc-400"}
                height={"20"}
                width={"20"}
                fill={"none"}
                stroke={"currentColor"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                strokeWidth={"2"}
                viewBox={"0 0 24 24"}
                xmlns={"http://www.w3.org/2000/svg"}
              >
                <path
                  d={"M18 6 6 18"}
                />
                <path
                  d={"m6 6 12 12"}
                />
              </svg>
            </button>
          </div>
          <div
            className={"mb-6"}
          >
            <label
              className={"block text-sm text-zinc-400 mb-2"}
            >
              {"Work Duration: " + (state.timer.workSecs / 60 | 0).toString() + " min"}
            </label>
            <input
              className={"w-full h-2 bg-zinc-800 rounded-lg appearance-none cursor-pointer accent-emerald-500"}
              max={"60"}
              min={"5"}
              step={5.0}
              type={"range"}
              value={(state.timer.workSecs / 60 | 0).toString()}
              onChange={e => {
                let value = Stdlib_Int.fromString(e.target.value, undefined);
                if (value !== undefined) {
                  return dispatch({
                    TAG: "UpdateWorkSecs",
                    _0: value * 60 | 0
                  });
                }
              }}
            />
          </div>
          <div
            className={"mb-6"}
          >
            <label
              className={"block text-sm text-zinc-400 mb-2"}
            >
              {"Break Duration: " + (state.timer.breakSecs / 60 | 0).toString() + " min"}
            </label>
            <input
              className={"w-full h-2 bg-zinc-800 rounded-lg appearance-none cursor-pointer accent-emerald-500"}
              max={"15"}
              min={"1"}
              step={1.0}
              type={"range"}
              value={(state.timer.breakSecs / 60 | 0).toString()}
              onChange={e => {
                let value = Stdlib_Int.fromString(e.target.value, undefined);
                if (value !== undefined) {
                  return dispatch({
                    TAG: "UpdateBreakSecs",
                    _0: value * 60 | 0
                  });
                }
              }}
            />
          </div>
        </div>
      </div> : null}
  </div>;
}

let make = App;

export {
  reducer,
  make,
}
/* react Not a pure module */
