// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./lib/utils";

function cn(prim0, prim1) {
  return Utils.cn(prim0, prim1);
}

function cn3(prim0, prim1, prim2) {
  return Utils.cn(prim0, prim1, prim2);
}

function cnv(prim) {
  return Utils.cn(...prim);
}

export {
  cn,
  cn3,
  cnv,
}
/* ./lib/utils Not a pure module */
