// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.jsx";
import * as React from "react";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

let root = document.querySelector("#root");

if (!(root == null)) {
  Client.createRoot(root, {
    onUncaughtError: e => {
      console.error("React uncaught error:", e);
    },
    onCaughtError: e => {
      console.error("React caught error:", e);
    }
  }).render(<React.StrictMode>
    <App.make />
  </React.StrictMode>);
}

/* root Not a pure module */
