// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function addTask(tasks, title, id) {
  let newTask = {
    id: id,
    title: title,
    done_: false
  };
  return tasks.concat([newTask]);
}

function toggleTask(tasks, id) {
  return Belt_Array.map(tasks, task => {
    if (task.id === id) {
      return {
        id: task.id,
        title: task.title,
        done_: !task.done_
      };
    } else {
      return task;
    }
  });
}

function deleteTask(tasks, id) {
  return Belt_Array.keep(tasks, task => task.id !== id);
}

function countDone(tasks) {
  return Belt_Array.reduce(tasks, 0, (acc, task) => {
    if (task.done_) {
      return acc + 1 | 0;
    } else {
      return acc;
    }
  });
}

export {
  addTask,
  toggleTask,
  deleteTask,
  countDone,
}
/* No side effect */
