// Generated by ReScript, PLEASE EDIT WITH CARE


function makeInitial(workSecs, breakSecs) {
  return {
    phase: "Idle",
    timeLeft: workSecs,
    workSecs: workSecs,
    breakSecs: breakSecs,
    sessionCount: 0
  };
}

function start(timer) {
  let match = timer.phase;
  if (match === "Idle") {
    return {
      phase: "Working",
      timeLeft: timer.timeLeft,
      workSecs: timer.workSecs,
      breakSecs: timer.breakSecs,
      sessionCount: timer.sessionCount
    };
  } else {
    return timer;
  }
}

function pause(timer) {
  let match = timer.phase;
  switch (match) {
    case "Working" :
    case "OnBreak" :
      break;
    case "Idle" :
    case "Paused" :
      return timer;
  }
  return {
    phase: "Paused",
    timeLeft: timer.timeLeft,
    workSecs: timer.workSecs,
    breakSecs: timer.breakSecs,
    sessionCount: timer.sessionCount
  };
}

function resume(timer) {
  let match = timer.phase;
  if (match === "Paused") {
    return {
      phase: "Working",
      timeLeft: timer.timeLeft,
      workSecs: timer.workSecs,
      breakSecs: timer.breakSecs,
      sessionCount: timer.sessionCount
    };
  } else {
    return timer;
  }
}

function reset(timer) {
  return {
    phase: "Idle",
    timeLeft: timer.workSecs,
    workSecs: timer.workSecs,
    breakSecs: timer.breakSecs,
    sessionCount: timer.sessionCount
  };
}

function tick(timer) {
  let match = timer.phase;
  switch (match) {
    case "Working" :
      if (timer.timeLeft > 1) {
        return [
          {
            phase: timer.phase,
            timeLeft: timer.timeLeft - 1 | 0,
            workSecs: timer.workSecs,
            breakSecs: timer.breakSecs,
            sessionCount: timer.sessionCount
          },
          false
        ];
      } else {
        return [
          {
            phase: "OnBreak",
            timeLeft: timer.breakSecs,
            workSecs: timer.workSecs,
            breakSecs: timer.breakSecs,
            sessionCount: timer.sessionCount + 1 | 0
          },
          true
        ];
      }
    case "OnBreak" :
      if (timer.timeLeft > 1) {
        return [
          {
            phase: timer.phase,
            timeLeft: timer.timeLeft - 1 | 0,
            workSecs: timer.workSecs,
            breakSecs: timer.breakSecs,
            sessionCount: timer.sessionCount
          },
          false
        ];
      } else {
        return [
          {
            phase: "Working",
            timeLeft: timer.workSecs,
            workSecs: timer.workSecs,
            breakSecs: timer.breakSecs,
            sessionCount: timer.sessionCount
          },
          true
        ];
      }
    case "Idle" :
    case "Paused" :
      return [
        timer,
        false
      ];
  }
}

function formatTime(seconds) {
  let mins = seconds / 60 | 0;
  let secs = seconds - (mins * 60 | 0) | 0;
  let minsStr = mins.toString();
  let secsStr = secs < 10 ? "0" + secs.toString() : secs.toString();
  return minsStr + ":" + secsStr;
}

export {
  makeInitial,
  start,
  pause,
  resume,
  reset,
  tick,
  formatTime,
}
/* No side effect */
