// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tasks from "../src/Tasks.res.jsx";
import * as Timer from "../src/Timer.res.jsx";
import * as Vitest from "rescript-vitest/src/Vitest.res.jsx";

Vitest.describe("Timer.makeInitial", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("creates idle timer with correct defaults", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let timer = Timer.makeInitial(1500, 300);
  t.expect(timer.phase).toBe("Idle");
  t.expect(timer.timeLeft).toBe(1500);
  t.expect(timer.sessionCount).toBe(0);
}));

Vitest.describe("Timer.start", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("transitions Idle to Working", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let timer = Timer.makeInitial(1500, 300);
  let t2 = Timer.start(timer);
  t.expect(t2.phase).toBe("Working");
  t.expect(t2.timeLeft).toBe(1500);
}));

Vitest.describe("Timer.pause", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("transitions Working to Paused", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let init = Timer.makeInitial(1500, 300);
    let timer_timeLeft = init.timeLeft;
    let timer_workSecs = init.workSecs;
    let timer_breakSecs = init.breakSecs;
    let timer_sessionCount = init.sessionCount;
    let timer = {
      phase: "Working",
      timeLeft: timer_timeLeft,
      workSecs: timer_workSecs,
      breakSecs: timer_breakSecs,
      sessionCount: timer_sessionCount
    };
    let t2 = Timer.pause(timer);
    t.expect(t2.phase).toBe("Paused");
  });
  Vitest.test("preserves timeLeft when pausing", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let init = Timer.makeInitial(1500, 300);
    let timer_workSecs = init.workSecs;
    let timer_breakSecs = init.breakSecs;
    let timer_sessionCount = init.sessionCount;
    let timer = {
      phase: "Working",
      timeLeft: 742,
      workSecs: timer_workSecs,
      breakSecs: timer_breakSecs,
      sessionCount: timer_sessionCount
    };
    let t2 = Timer.pause(timer);
    t.expect(t2.timeLeft).toBe(742);
  });
  Vitest.test("no-op when already Idle", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let timer = Timer.makeInitial(1500, 300);
    let t2 = Timer.pause(timer);
    t.expect(t2.phase).toBe("Idle");
  });
});

Vitest.describe("Timer.resume", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("transitions Paused to Working", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
  let init = Timer.makeInitial(1500, 300);
  let timer_workSecs = init.workSecs;
  let timer_breakSecs = init.breakSecs;
  let timer_sessionCount = init.sessionCount;
  let timer = {
    phase: "Paused",
    timeLeft: 600,
    workSecs: timer_workSecs,
    breakSecs: timer_breakSecs,
    sessionCount: timer_sessionCount
  };
  let t2 = Timer.resume(timer);
  t.expect(t2.phase).toBe("Working");
  t.expect(t2.timeLeft).toBe(600);
}));

Vitest.describe("Timer.reset", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("resets to Idle with original workSecs", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let init = Timer.makeInitial(1500, 300);
    let timer_workSecs = init.workSecs;
    let timer_breakSecs = init.breakSecs;
    let timer_sessionCount = init.sessionCount;
    let timer = {
      phase: "Working",
      timeLeft: 42,
      workSecs: timer_workSecs,
      breakSecs: timer_breakSecs,
      sessionCount: timer_sessionCount
    };
    let t2 = Timer.reset(timer);
    t.expect(t2.phase).toBe("Idle");
    t.expect(t2.timeLeft).toBe(1500);
  });
  Vitest.test("preserves sessionCount on reset", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let init = Timer.makeInitial(1500, 300);
    let timer_phase = init.phase;
    let timer_timeLeft = init.timeLeft;
    let timer_workSecs = init.workSecs;
    let timer_breakSecs = init.breakSecs;
    let timer = {
      phase: timer_phase,
      timeLeft: timer_timeLeft,
      workSecs: timer_workSecs,
      breakSecs: timer_breakSecs,
      sessionCount: 3
    };
    let t2 = Timer.reset(timer);
    t.expect(t2.sessionCount).toBe(3);
  });
});

Vitest.describe("Timer.tick", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("decrements timeLeft by 1 while Working", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let init = Timer.makeInitial(1500, 300);
    let timer_workSecs = init.workSecs;
    let timer_breakSecs = init.breakSecs;
    let timer_sessionCount = init.sessionCount;
    let timer = {
      phase: "Working",
      timeLeft: 10,
      workSecs: timer_workSecs,
      breakSecs: timer_breakSecs,
      sessionCount: timer_sessionCount
    };
    let match = Timer.tick(timer);
    t.expect(match[0].timeLeft).toBe(9);
    t.expect(match[1]).toBe(false);
  });
  Vitest.test("decrements timeLeft by 1 while OnBreak", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let init = Timer.makeInitial(1500, 300);
    let timer_workSecs = init.workSecs;
    let timer_breakSecs = init.breakSecs;
    let timer_sessionCount = init.sessionCount;
    let timer = {
      phase: "OnBreak",
      timeLeft: 5,
      workSecs: timer_workSecs,
      breakSecs: timer_breakSecs,
      sessionCount: timer_sessionCount
    };
    let match = Timer.tick(timer);
    t.expect(match[0].timeLeft).toBe(4);
    t.expect(match[1]).toBe(false);
  });
  Vitest.test("signals completion and starts break when Working reaches 0", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let init = Timer.makeInitial(1500, 300);
    let timer_workSecs = init.workSecs;
    let timer_breakSecs = init.breakSecs;
    let timer_sessionCount = init.sessionCount;
    let timer = {
      phase: "Working",
      timeLeft: 1,
      workSecs: timer_workSecs,
      breakSecs: timer_breakSecs,
      sessionCount: timer_sessionCount
    };
    let match = Timer.tick(timer);
    let t2 = match[0];
    t.expect(match[1]).toBe(true);
    t.expect(t2.sessionCount).toBe(1);
    t.expect(t2.phase).toBe("OnBreak");
    t.expect(t2.timeLeft).toBe(300);
  });
  Vitest.test("signals completion and returns to Working when OnBreak reaches 0", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let init = Timer.makeInitial(1500, 300);
    let timer_workSecs = init.workSecs;
    let timer_breakSecs = init.breakSecs;
    let timer_sessionCount = init.sessionCount;
    let timer = {
      phase: "OnBreak",
      timeLeft: 1,
      workSecs: timer_workSecs,
      breakSecs: timer_breakSecs,
      sessionCount: timer_sessionCount
    };
    let match = Timer.tick(timer);
    let t2 = match[0];
    t.expect(match[1]).toBe(true);
    t.expect(t2.phase).toBe("Working");
    t.expect(t2.timeLeft).toBe(1500);
  });
  Vitest.test("no-op when Idle", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let timer = Timer.makeInitial(1500, 300);
    let match = Timer.tick(timer);
    t.expect(match[0].phase).toBe("Idle");
    t.expect(match[1]).toBe(false);
  });
  Vitest.test("no-op when Paused", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let init = Timer.makeInitial(1500, 300);
    let timer_workSecs = init.workSecs;
    let timer_breakSecs = init.breakSecs;
    let timer_sessionCount = init.sessionCount;
    let timer = {
      phase: "Paused",
      timeLeft: 100,
      workSecs: timer_workSecs,
      breakSecs: timer_breakSecs,
      sessionCount: timer_sessionCount
    };
    let match = Timer.tick(timer);
    t.expect(match[0].timeLeft).toBe(100);
    t.expect(match[1]).toBe(false);
  });
});

Vitest.describe("Timer.formatTime", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("formats 90 seconds as 1:30", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Timer.formatTime(90)).toBe("1:30"));
  Vitest.test("formats 0 as 0:00", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Timer.formatTime(0)).toBe("0:00"));
  Vitest.test("formats 1500 as 25:00", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Timer.formatTime(1500)).toBe("25:00"));
  Vitest.test("pads single-digit seconds", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Timer.formatTime(61)).toBe("1:01"));
});

Vitest.describe("Tasks.addTask", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("adds a new task with given title", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tasks = Tasks.addTask([], "Buy groceries", 1);
    t.expect(tasks.length).toBe(1);
    let task = tasks[0];
    if (task !== undefined) {
      t.expect(task.title).toBe("Buy groceries");
      t.expect(task.done_).toBe(false);
      return t.expect(task.id).toBe(1);
    } else {
      return t.expect("got None").toBe("expected task");
    }
  });
  Vitest.test("appends to existing tasks", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tasks = Tasks.addTask(Tasks.addTask([], "First", 1), "Second", 2);
    t.expect(tasks.length).toBe(2);
  });
});

Vitest.describe("Tasks.toggleTask", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("marks an incomplete task as done", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tasks = Tasks.addTask([], "Write tests", 1);
    let tasks2 = Tasks.toggleTask(tasks, 1);
    let task = tasks2[0];
    if (task !== undefined) {
      return t.expect(task.done_).toBe(true);
    } else {
      return t.expect("got None").toBe("expected task");
    }
  });
  Vitest.test("marks a done task as incomplete", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tasks = Tasks.toggleTask(Tasks.toggleTask(Tasks.addTask([], "Write tests", 1), 1), 1);
    let task = tasks[0];
    if (task !== undefined) {
      return t.expect(task.done_).toBe(false);
    } else {
      return t.expect("got None").toBe("expected task");
    }
  });
  Vitest.test("only toggles the targeted task", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tasks = Tasks.toggleTask(Tasks.addTask(Tasks.addTask([], "First", 1), "Second", 2), 1);
    let task = tasks[1];
    if (task !== undefined) {
      return t.expect(task.done_).toBe(false);
    } else {
      return t.expect("got None").toBe("expected task");
    }
  });
});

Vitest.describe("Tasks.deleteTask", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("removes the task with matching id", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tasks = Tasks.deleteTask(Tasks.addTask(Tasks.addTask([], "Keep", 1), "Delete me", 2), 2);
    t.expect(tasks.length).toBe(1);
    let task = tasks[0];
    if (task !== undefined) {
      return t.expect(task.title).toBe("Keep");
    } else {
      return t.expect("got None").toBe("expected task");
    }
  });
  Vitest.test("no-op when id not found", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tasks = Tasks.deleteTask(Tasks.addTask([], "Task", 1), 99);
    t.expect(tasks.length).toBe(1);
  });
});

Vitest.describe("Tasks.countDone", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("counts completed tasks", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let tasks = Tasks.toggleTask(Tasks.toggleTask(Tasks.addTask(Tasks.addTask(Tasks.addTask([], "A", 1), "B", 2), "C", 3), 1), 3);
    t.expect(Tasks.countDone(tasks)).toBe(2);
  });
  Vitest.test("returns 0 for empty list", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => t.expect(Tasks.countDone([])).toBe(0));
});

/*  Not a pure module */
